const app = document.querySelector('#app')

const lessons = [
  {
    id:1, icon:'🌱', tone:'green', title:'AI 發展趨勢', sub:'從規則、學習、生成，到自主行動',
    slides:[
      {k:'01 · AI 發展趨勢',t:'AI 不是突然出現，而是能力一層一層往上堆',b:`<p class="lead">看 AI 發展，不要只背年份；更重要的是看「人要先寫多少規則」與「機器可以自己完成多少工作」。</p><div class="timeline" id="trend"><button class="time-node active" data-i="0"><small>早期</small><b>規則式 AI</b></button><button class="time-node" data-i="1"><small>資料驅動</small><b>機器學習</b></button><button class="time-node" data-i="2"><small>深度表徵</small><b>深度學習</b></button><button class="time-node" data-i="3"><small>2022 後普及</small><b>生成式 AI</b></button><button class="time-node" data-i="4"><small>現在進行式</small><b>AI Agent</b></button></div><div class="big-idea" id="trendDetail">規則式 AI：人先把判斷條件寫清楚，機器照規則執行。適合條件穩定、可明確定義的問題。</div>`},
      {k:'看懂差異',t:'真正的變化，是「規則」慢慢轉成「目標」',b:`<div class="grid2"><div class="concept-card"><div class="emoji">🧾</div><h3>過去：告訴機器每一步怎麼做</h3><p>例如：溫度超過 80°C 就警報；庫存小於安全量就補貨。</p></div><div class="concept-card"><div class="emoji">🎯</div><h3>現在：告訴 AI 目標與限制</h3><p>例如：分析異常、找原因、查資料、提出處置建議，必要時再呼叫工具。</p></div></div><div class="big-idea">AI 越往後發展，人的工作越從「寫死流程」轉向「定義目標、提供情境、設定邊界與驗證結果」。</div>`},
      {k:'企業視角',t:'從模型能力，走向系統能力',b:`<div class="flow"><div class="flow-step"><b>Model</b><span>會回答</span></div><div class="arrow">→</div><div class="flow-step"><b>RAG</b><span>會查企業知識</span></div><div class="arrow">→</div><div class="flow-step"><b>Tool</b><span>會呼叫系統</span></div><div class="arrow">→</div><div class="flow-step"><b>Agent</b><span>會規劃與行動</span></div><div class="arrow">→</div><div class="flow-step"><b>Governance</b><span>可控、可稽核</span></div></div><div class="big-idea">企業真正買單的，不只是「模型很聰明」，而是它能不能安全接上資料、流程與權限。</div>`},
      {k:'一句話收斂',t:'生成式 AI 的下一站，是「能做事」的 AI',b:`<p class="lead">大型語言模型讓 AI 從辨識與預測，進一步具備生成與推理能力；Agent 再把這些能力接到工具與流程。</p><div class="grid3"><div class="concept-card"><div class="emoji">💬</div><h3>生成</h3><p>產生文字、圖片、程式與結構化資料。</p></div><div class="concept-card"><div class="emoji">🧠</div><h3>推理</h3><p>依問題拆解步驟、比較選項、形成計畫。</p></div><div class="concept-card"><div class="emoji">🛠️</div><h3>行動</h3><p>呼叫工具、查系統、執行任務，再讀取結果。</p></div></div>`}
    ]
  },
  {
    id:2, icon:'🧠', tone:'blue', title:'LLM 基礎觀念', sub:'文字接龍、Token、Attention、訓練、Prompt、RAG',
    slides:[
      {k:'02 · LLM 基礎',t:'LLM 的核心其實很像「超強文字接龍」',b:`<p class="lead">大型語言模型（LLM, Large Language Model）每次做的核心工作，是根據前面的內容預測下一個最可能的 Token。</p><div class="demo"><b>「今天下班後，我想去喝一杯…」下一個詞可能是？</b><div class="bar-row"><span>咖啡</span><div class="bar"><i style="width:48%"></i></div><strong>48%</strong></div><div class="bar-row"><span>奶茶</span><div class="bar"><i style="width:28%"></i></div><strong>28%</strong></div><div class="bar-row"><span>啤酒</span><div class="bar"><i style="width:15%"></i></div><strong>15%</strong></div><div class="bar-row"><span>水</span><div class="bar"><i style="width:9%"></i></div><strong>9%</strong></div></div><div class="big-idea">它不是一次把整句話想完，而是「預測一個 → 加回上下文 → 再預測下一個」。</div>`},
      {k:'Token',t:'模型不是直接讀「字」，而是先切成 Token',b:`<p class="lead">Token（詞元）是模型處理文字的基本單位。它可能是一個中文字、英文單字的一部分、標點，甚至空白。</p><div class="demo"><label><b>試著換一句話：</b></label><input id="tokenInput" value="我正在學習生成式 AI" style="width:100%;margin-top:12px;padding:13px 15px;border:1px solid #ddd8cc;border-radius:12px;font-size:18px"><div class="token-row" id="tokenRow"></div></div><div class="big-idea">Token 數量會影響 Context Window（上下文視窗）、速度與 API 成本。</div>`},
      {k:'Self-Attention',t:'Self-Attention：這個字現在應該注意誰？',b:`<p class="lead">Self-Attention（自注意力機制）讓句子裡每個 Token 都能依情境，去衡量其他 Token 對自己的重要程度。</p><div class="demo"><b>句子：「小明把筆電交給小華，因為他要報告。」</b><p>點選候選詞，看看「他」可能注意誰：</p><div class="attention-row"><button class="attn-token active" data-name="小明" data-score="72">小明</button><button class="attn-token" data-name="筆電" data-score="8">筆電</button><button class="attn-token" data-name="小華" data-score="20">小華</button></div><div class="big-idea" id="attnDetail">目前示意：模型可能給「小明」較高注意力，因為語意上更像「要報告」的主體。真正模型會由 Q、K 的匹配分數計算權重，再加權 V。</div></div>`},
      {k:'Q / K / V',t:'Q、K、V 可以先記成三句人話',b:`<div class="grid3"><div class="concept-card"><div class="emoji">❓</div><h3>Q · Query</h3><p>我現在想找什麼？</p></div><div class="concept-card"><div class="emoji">🏷️</div><h3>K · Key</h3><p>我有哪些線索可以跟你配對？</p></div><div class="concept-card"><div class="emoji">📦</div><h3>V · Value</h3><p>如果你注意到我，我真正提供什麼內容？</p></div></div><div class="flow"><div class="flow-step"><b>Q × K</b><span>算匹配分數</span></div><div class="arrow">→</div><div class="flow-step"><b>Softmax</b><span>轉成權重</span></div><div class="arrow">→</div><div class="flow-step"><b>加權 V</b><span>組合需要的資訊</span></div></div>`},
      {k:'Training',t:'LLM 怎麼被訓練出來？',b:`<div class="flow"><div class="flow-step"><b>1. Pretraining</b><span>大量資料學語言與世界模式</span></div><div class="arrow">→</div><div class="flow-step"><b>2. SFT</b><span>Supervised Fine-Tuning<br>監督式微調</span></div><div class="arrow">→</div><div class="flow-step"><b>3. Preference</b><span>學人類偏好的回答</span></div><div class="arrow">→</div><div class="flow-step"><b>4. Alignment</b><span>對齊安全與行為要求</span></div></div><div class="big-idea">Pretraining 讓模型「會語言」；後續訓練讓它更像一個能遵循指令、符合期待的助手。</div>`},
      {k:'Prompt',t:'Prompt 不只是「怎麼問」，而是設計 AI 的工作環境',b:`<div class="grid2"><div class="concept-card"><h3>弱 Prompt</h3><p>「幫我分析這份報表。」</p></div><div class="concept-card"><h3>強 Prompt</h3><p>交代角色、目標、背景、資料、限制、輸出格式、判斷規則與工具。</p></div></div><div class="topic-list"><div class="topic-pill">System Prompt：長期規則與角色</div><div class="topic-pill">User Prompt：這次要完成的任務</div><div class="topic-pill">Context：這次可用的背景與資料</div><div class="topic-pill">Output Schema：結果要長什麼樣子</div></div><div class="big-idea">越重要的任務，越不要只靠一句漂亮 Prompt；要把資料、工具、權限與輸出規格一起設計。</div>`},
      {k:'RAG',t:'RAG：先找資料，再讓 LLM 根據資料回答',b:`<p class="lead">RAG（Retrieval-Augmented Generation，檢索增強生成）解決的是：企業知識不一定存在模型參數裡，也可能每天更新。</p><div class="flow"><div class="flow-step"><b>問題</b><span>OC715 為何異常？</span></div><div class="arrow">→</div><div class="flow-step"><b>Retrieve</b><span>檢索相關文件</span></div><div class="arrow">→</div><div class="flow-step"><b>Context</b><span>把證據交給 LLM</span></div><div class="arrow">→</div><div class="flow-step"><b>Generate</b><span>根據證據回答</span></div><div class="arrow">→</div><div class="flow-step"><b>Citation</b><span>附來源</span></div></div><div class="big-idea">RAG 不是讓模型「變聰明」，而是讓它回答前先拿到更可靠、更新、更貼近企業情境的資料。</div>`},
      {k:'串起來',t:'LLM 應用不是一個模型，而是一條資料與決策鏈',b:`<div class="flow"><div class="flow-step"><b>Token</b><span>文字變成模型單位</span></div><div class="arrow">→</div><div class="flow-step"><b>Attention</b><span>理解上下文關係</span></div><div class="arrow">→</div><div class="flow-step"><b>Prompt</b><span>定義任務與限制</span></div><div class="arrow">→</div><div class="flow-step"><b>RAG</b><span>補企業證據</span></div><div class="arrow">→</div><div class="flow-step"><b>Output</b><span>生成回答或指令</span></div></div>`}
    ]
  },
  {
    id:3, icon:'🤖', tone:'sand', title:'AI Agent 觀念', sub:'目標、推理、工具、MCP、Skill',
    slides:[
      {k:'03 · AI Agent',t:'Agent 不只是回答，它會為了目標「決定下一步」',b:`<p class="lead">AI Agent（AI 代理）通常由 LLM 擔任決策核心，根據目標與目前狀態，決定要不要查資料、呼叫工具、重試或結束。</p><div class="flow"><div class="flow-step"><b>Goal</b><span>收到目標</span></div><div class="arrow">→</div><div class="flow-step"><b>Reason</b><span>判斷下一步</span></div><div class="arrow">→</div><div class="flow-step"><b>Act</b><span>呼叫工具</span></div><div class="arrow">→</div><div class="flow-step"><b>Observe</b><span>讀取結果</span></div><div class="arrow">↺</div></div><div class="big-idea">關鍵不是「會不會聊天」，而是系統是否允許模型根據狀態動態選擇行動。</div>`},
      {k:'Agent 組成',t:'一個能上線的 Agent，至少要有這些東西',b:`<div class="grid3"><div class="concept-card"><div class="emoji">🧠</div><h3>Model</h3><p>理解、推理、規劃。</p></div><div class="concept-card"><div class="emoji">📚</div><h3>Context / Memory</h3><p>取得任務背景與必要記憶。</p></div><div class="concept-card"><div class="emoji">🛠️</div><h3>Tools</h3><p>真正查詢或改變外部世界。</p></div></div><div class="grid3"><div class="concept-card"><div class="emoji">🧭</div><h3>Policy</h3><p>哪些事情可以做、不能做。</p></div><div class="concept-card"><div class="emoji">✅</div><h3>Evaluation</h3><p>怎麼知道結果可信。</p></div><div class="concept-card"><div class="emoji">🧾</div><h3>Audit</h3><p>留下可追蹤的決策與操作紀錄。</p></div></div>`},
      {k:'MCP',t:'MCP：讓模型用一致方式連接外部能力',b:`<p class="lead"><span class="accent">MCP（Model Context Protocol，模型情境協定）</span>可以把外部資料、工具與資源，用一致介面提供給 AI 應用。</p><div class="grid2"><div class="concept-card"><h3>沒有 MCP</h3><p>每個模型 × 每個系統都各寫一套串接，整合容易變成蜘蛛網。</p></div><div class="concept-card"><h3>有 MCP</h3><p>把工具與資源標準化暴露，AI 端用共同協定發現與使用。</p></div></div><div class="big-idea">MCP 解的是「怎麼接」；它不等於 Agent，也不會自動幫你定義商業流程。</div>`},
      {k:'Skill',t:'Skill：把一件事做好的方法封裝起來',b:`<p class="lead"><span class="accent">Skill（技能模組）</span>可以理解成「完成某類任務所需的指令、工具用法、流程與規則」的可重用封裝。</p><table class="compare"><tr><th>概念</th><th>主要回答的問題</th></tr><tr><td>MCP</td><td>模型如何取得外部工具與資源？</td></tr><tr><td>Skill</td><td>面對某類任務，應該怎麼做才做得好？</td></tr><tr><td>Agent</td><td>根據目標與狀態，現在應該採取哪個行動？</td></tr></table><div class="big-idea">可以把 MCP 想成「插座規格」，Skill 想成「標準作業能力」，Agent 則是「會判斷何時用哪個能力的人」。</div>`},
      {k:'Agent Demo',t:'Agent 的價值，是可以根據結果改變下一步',b:`<div class="demo"><p><b>任務：</b>找出昨天產線停機最可能原因，並提出下一步。</p><button class="button primary" id="agentRun">執行一次 Agent Loop</button><div id="agentLog" style="margin-top:18px;line-height:1.8;color:#5e6861">尚未執行。</div></div><div class="big-idea">真正上線時，重要動作通常還要搭配權限、人工確認、重試上限與稽核紀錄。</div>`}
    ]
  },
  {
    id:4, icon:'🧭', tone:'lavender', title:'Workflow 與 AI Agent 差異', sub:'固定流程 vs 動態決策，以及何時混用',
    slides:[
      {k:'04 · Workflow vs Agent',t:'最重要的差異：下一步是誰決定的？',b:`<div class="grid2"><div class="concept-card"><div class="emoji">🛤️</div><h3>Workflow</h3><p>設計者事先決定流程。A 完成後固定走 B；條件成立走 C。</p></div><div class="concept-card"><div class="emoji">🤖</div><h3>AI Agent</h3><p>系統給目標與可用工具，模型根據目前狀態動態決定下一步。</p></div></div><div class="big-idea">Workflow 的核心是「控制流程」；Agent 的核心是「授權決策」。</div>`},
      {k:'逐項比較',t:'不是誰比較高級，而是風險與任務形狀不同',b:`<table class="compare"><tr><th>面向</th><th>Workflow</th><th>AI Agent</th></tr><tr><td>路徑</td><td>預先定義</td><td>動態決定</td></tr><tr><td>可預測性</td><td>高</td><td>較低</td></tr><tr><td>彈性</td><td>中</td><td>高</td></tr><tr><td>測試</td><td>容易做流程測試</td><td>需做情境與行為評估</td></tr><tr><td>適合</td><td>穩定、規則清楚、高風險流程</td><td>資訊不完整、路徑不固定、需要推理的工作</td></tr></table>`},
      {k:'情境一',t:'哪些事情應該優先用 Workflow？',b:`<div class="grid3"><div class="concept-card"><h3>薪資入帳</h3><p>步驟固定、錯誤成本高。</p></div><div class="concept-card"><h3>正式 SAP 過帳</h3><p>需明確規則、權限與可追溯性。</p></div><div class="concept-card"><h3>設備停機保護</h3><p>即時、確定性優先，不適合讓 LLM 自由判斷。</p></div></div><div class="big-idea">越接近「不可逆、高風險、法遵、即時控制」，越應把關鍵路徑鎖在 Workflow 或傳統程式。</div>`},
      {k:'情境二',t:'哪些事情適合交給 Agent？',b:`<div class="grid3"><div class="concept-card"><h3>異常原因調查</h3><p>需要跨文件、跨系統蒐集線索。</p></div><div class="concept-card"><h3>客訴前置分析</h3><p>案例不固定，需要整理背景與提出建議。</p></div><div class="concept-card"><h3>維修助理</h3><p>根據設備、歷史紀錄與現象動態找下一步。</p></div></div><div class="big-idea">越是「資訊很多、路徑未知、需要探索與判斷」，越能發揮 Agent 的價值。</div>`},
      {k:'最佳實務',t:'企業真正常用的答案：Workflow + Agent 混合',b:`<div class="flow"><div class="flow-step"><b>Workflow</b><span>接收事件、做基本檢查</span></div><div class="arrow">→</div><div class="flow-step"><b>Agent</b><span>分析、查資料、提出方案</span></div><div class="arrow">→</div><div class="flow-step"><b>Human Gate</b><span>高風險動作人工確認</span></div><div class="arrow">→</div><div class="flow-step"><b>Workflow</b><span>執行正式異動</span></div></div><div class="big-idea">讓 Agent 處理「需要智慧的模糊區」，讓 Workflow 守住「必須確定的控制點」。</div>`},
      {k:'小測驗',t:'最後一題：你會選 Workflow 還是 Agent？',b:`<p class="lead">需求：每天自動整理各系統前一天的異常，先判斷哪些值得追查；必要時查維修紀錄與 SOP，產生原因假設，但「不得自動修改設備參數」。</p><div class="quiz-options"><button data-answer="w">A. 全部寫死成 Workflow</button><button data-answer="a">B. 全部交給 Agent，自動修改設備</button><button data-answer="h">C. Workflow 觸發 + Agent 分析 + 人工確認</button></div><div class="result" id="quizResult"></div>`}
    ]
  }
]

function nav(){return `<header class="topbar"><div class="shell nav"><a class="brand" href="#/"><span class="brandmark">☘</span><span><b>AI Essentials</b><small>用白話，先把 AI 的骨架學懂</small></span></a><nav class="navlinks">${lessons.map(x=>`<a href="#/lesson/${x.id}/1">${x.id}. ${x.title}</a>`).join('')}</nav></div></header>`}

function home(){app.innerHTML=`${nav()}<main><section class="home-hero"><div class="shell hero-grid"><div class="hero-copy"><span class="scribble">只教真正需要先懂的核心。</span><h1>先把 AI 的<br><em>骨架學懂</em></h1><p>從 AI 發展趨勢，到 LLM、Agent，最後學會判斷：什麼該用 Workflow，什麼才需要 Agent。</p><div class="hero-actions"><a class="button primary" href="#/lesson/1/1">開始學習 →</a><a class="button secondary" href="#/lesson/2/1">直接看 LLM 基礎</a></div></div><div class="hero-art-wrap"><div class="sticky sticky-a">白話</div><div class="sticky sticky-b">原理</div><div class="sticky sticky-c">落地</div><img class="hero-art" src="../assets/hero-desk.webp" alt="學習桌插畫"></div></div></section><section class="stage-section"><div class="shell stage-grid">${lessons.map(x=>`<a class="stage-card ${x.tone}" href="#/lesson/${x.id}/1"><span class="stage-icon">${x.icon}</span><div><b>${x.id}. ${x.title}</b><small>${x.sub}</small></div></a>`).join('')}</div></section><div class="shell footer-note">AI Essentials · 適合課堂投影與企業入門教學</div></main>`}
}

function lesson(id,page){const l=lessons.find(x=>x.id===id)||lessons[0];const p=Math.max(1,Math.min(page,l.slides.length));const s=l.slides[p-1];app.innerHTML=`${nav()}<main class="lesson-page"><div class="shell lesson-shell"><div class="lesson-meta"><a href="#/">首頁</a><span>›</span><b>${l.id}. ${l.title}</b><div class="lesson-progress"><strong>${p} / ${l.slides.length}</strong><i><b style="width:${p/l.slides.length*100}%"></b></i></div></div><section class="slide"><span class="slide-kicker">${s.k}</span><h2>${s.t}</h2>${s.b}</section><div class="slide-nav"><div class="page-dots">${l.slides.map((_,i)=>`<a class="${i+1===p?'active':''}" href="#/lesson/${l.id}/${i+1}"></a>`).join('')}</div><div>${p>1?`<a class="button secondary" href="#/lesson/${l.id}/${p-1}">← 上一頁</a>`:`<a class="button secondary" href="#/">← 首頁</a>`} ${p<l.slides.length?`<a class="button primary" href="#/lesson/${l.id}/${p+1}">下一頁 →</a>`:l.id<lessons.length?`<a class="button primary" href="#/lesson/${l.id+1}/1">下一主題 →</a>`:`<a class="button primary" href="#/">完成課程 ✓</a>`}</div></div></div></main>`;wire()}

function wire(){
  document.querySelectorAll('#trend .time-node').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('#trend .time-node').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const texts=['規則式 AI：人先把判斷條件寫清楚，機器照規則執行。適合條件穩定、可明確定義的問題。','機器學習：不再手寫所有規則，而是提供資料，讓模型學出分類或預測模式。','深度學習：多層神經網路自動學習更複雜的特徵，帶動影像、語音與 NLP 能力大幅提升。','生成式 AI：模型開始能根據上下文生成文字、圖片、程式等新內容，人機介面大幅改變。','AI Agent：模型不只生成答案，而是能根據目標使用資料與工具，反覆觀察結果並決定下一步。'];document.querySelector('#trendDetail').textContent=texts[Number(btn.dataset.i)]}))
  const input=document.querySelector('#tokenInput');if(input){const draw=()=>{const text=input.value.trim();const tokens=text.match(/[A-Za-z]+|[\u4e00-\u9fff]|\d+|[^\s]/g)||[];document.querySelector('#tokenRow').innerHTML=tokens.map(x=>`<span class="token">${x}</span>`).join('')};input.addEventListener('input',draw);draw()}
  document.querySelectorAll('.attn-token').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.attn-token').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#attnDetail').textContent=`示意注意力：對「${btn.dataset.name}」給 ${btn.dataset.score}% 權重。重點不是這個固定數字，而是模型會依上下文動態重新計算關係。`}))
  const run=document.querySelector('#agentRun');if(run)run.addEventListener('click',()=>{document.querySelector('#agentLog').innerHTML='① 讀取昨日停機事件 → ② 查詢設備歷史告警 → ③ 發現主軸過溫重複出現 → ④ 查維修紀錄與 SOP → ⑤ 建議先檢查冷卻與潤滑；<b>不直接修改設備參數</b>。';run.textContent='再執行一次'})
  document.querySelectorAll('.quiz-options button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.quiz-options button').forEach(x=>x.classList.remove('correct','wrong'));const ok=btn.dataset.answer==='h';btn.classList.add(ok?'correct':'wrong');document.querySelector('#quizResult').textContent=ok?'✓ 最合理：固定的觸發與控制點交給 Workflow，探索與分析交給 Agent，高風險動作保留人工確認。':'再想一次：題目同時包含固定觸發、動態分析與高風險限制，因此最適合混合架構。'}))
}

function route(){const p=(location.hash||'#/').replace(/^#\//,'').split('/').filter(Boolean);if(p[0]==='lesson')lesson(Number(p[1])||1,Number(p[2])||1);else home()}
window.addEventListener('hashchange',route)
window.addEventListener('keydown',e=>{const p=(location.hash||'').replace(/^#\//,'').split('/').filter(Boolean);if(p[0]!=='lesson')return;const id=Number(p[1]),page=Number(p[2]),l=lessons.find(x=>x.id===id);if(!l)return;if(e.key==='ArrowRight'){if(page<l.slides.length)location.hash=`#/lesson/${id}/${page+1}`;else if(id<lessons.length)location.hash=`#/lesson/${id+1}/1`}if(e.key==='ArrowLeft'){if(page>1)location.hash=`#/lesson/${id}/${page-1}`;else if(id>1){const prev=lessons[id-2];location.hash=`#/lesson/${id-1}/${prev.slides.length}`}}})
route()
